name: helm promote

on: workflow_dispatch

jobs:
  helm-promote:
    runs-on: ubuntu-latest
    env:
      MAGMA_VERSION: 1.8.0
      HELM_CHART_MUSEUM_TOKEN: ${{ secrets.HELM_CHART_MUSEUM_TOKEN }}
      HELM_CHART_MUSEUM_USERNAME: ${{ secrets.HELM_CHART_MUSEUM_USERNAME }}
    steps:
      - run: |
        git clone https://github.com/magma/magma.git --depth 1
        cd magma/orc8r/tools/helm
        
        # Promote Helm charts
        ./promote.sh orc8r-${MAGMA_VERSION}.tgz
        ./promote.sh cwf-orc8r-${MAGMA_VERSION}.tgz
        ./promote.sh fbinternal-orc8r-${MAGMA_VERSION}.tgz
        ./promote.sh feg-orc8r-${MAGMA_VERSION}.tgz
        ./promote.sh lte-orc8r-${MAGMA_VERSION}.tgz
        ./promote.sh domain-proxy-${MAGMA_VERSION}.tgz
